export type Language = 'en' | 'zh';

export const translations = {
  en: {
    // Navigation
    workspace: 'Workspace',
    back: 'Back',
    reset: 'Reset',
    copyResult: 'Copy Result',
    copied: 'Copied',
    
    // Homepage
    tagline: 'Next Generation Resume Analysis',
    heroTitle: 'Craft the perfect resume.',
    heroSubtitle: 'With the analytical depth of AI, reshape your career narrative',
    heroDesc: 'Place your background alongside your target role. Our AI analyzes the gap, extracts your core value, and provides editorial-grade refinement.',
    startDiagnosis: 'Start Diagnosis',
    
    // Settings
    settings: 'Settings',
    configApi: 'API Configuration',
    configApiDesc: 'Configure your custom OpenAI-compatible API credentials. Keys are stored locally.',
    baseUrl: 'Base URL',
    apiKey: 'API Key',
    model: 'Model',
    save: 'Save',
    cancel: 'Cancel',
    testConnection: 'Test Connection',
    testing: 'Testing...',
    testSuccess: 'Success!',
    testFailed: 'Failed',

    feature1Title: 'Intelligent Resume Parsing',
    feature1Desc: 'Deeply understand your career trajectory and extract core competencies.',
    feature2Title: 'Precision Job Matching',
    feature2Desc: 'Evaluate your background against specific job requirements with analytical rigor.',
    feature3Title: 'Editorial Refinement',
    feature3Desc: 'Receive actionable, highly-quantified rewrite suggestions engineered for impact.',
    
    footer: 'Anthropic-inspired UI • ResumeAI Pro © 2026',

    // Dashboard
    analysisConfig: 'Analysis Configuration',
    analysisDesc: 'Provide your current draft and the target job description to begin the editorial process.',
    currentDraft: 'Current Draft',
    jd: 'Target Job Description',
    resumePlaceholder: 'Paste your resume content in markdown or plain text...\n\nIncludes:\n· Professional Setup\n· Work Experience\n· Education\n· Skills',
    jdPlaceholder: 'Paste the job description...\n\nIncludes:\n· Key Responsibilities\n· Required Qualifications\n· Preferred Stack',
    generateAnalysis: 'Generate Analysis',
    synthesizing: 'Synthesizing...',
    analysisReport: 'Analysis Report',
    generatedBy: 'Generated by Resume AI',
    waitingInput: 'Waiting for input. The analysis will be rendered with editorial precision.',
    chars: 'chars',
  },
  zh: {
    // Navigation
    workspace: '工作台',
    back: '返回',
    reset: '重置',
    copyResult: '复制结果',
    copied: '已复制',
    
    // Homepage
    tagline: '新一代简历分析引擎',
    heroTitle: '打造完美的求职简历',
    heroSubtitle: '以 AI 的分析深度，重塑你的职场叙事',
    heroDesc: '粘贴个人履历和目标岗位描述。我们的 AI 将分析差距，提取核心竞争力，并提供编辑级的润色建议。',
    startDiagnosis: '开始诊断',
    
    // Settings
    settings: '设置',
    configApi: 'API 配置',
    configApiDesc: '配置自定义的 OpenAI 兼容 API。密钥仅保存在您的本地浏览器中。',
    baseUrl: '接口地址 (Base URL)',
    apiKey: '密钥 (API Key)',
    model: '模型名称 (Model)',
    save: '保存',
    cancel: '取消',
    testConnection: '连通性测试',
    testing: '测试中...',
    testSuccess: '连通成功！',
    testFailed: '连通失败',

    feature1Title: '深度简历解析',
    feature1Desc: '深度理解您的职业轨迹，并精准提取核心竞争力。',
    feature2Title: '高压精准匹配',
    feature2Desc: '以专业分析的严谨性，将您的背景与特定职位要求进行逐条对比评估。',
    feature3Title: '编辑级润色',
    feature3Desc: '获得具备高度量化、且极具实际操作性的优化与重写建议。',
    
    footer: '基于 Anthropic 设计美学 • ResumeAI Pro © 2026',

    // Dashboard
    analysisConfig: '分析配置',
    analysisDesc: '请提供您当前的简历草稿与目标职位 JD，以开启编辑级润色流程。',
    currentDraft: '当前简历草稿',
    jd: '目标岗位描述 (JD)',
    resumePlaceholder: '在此粘贴 Markdown 或纯文本格式的简历...\n\n建议包含：\n· 个人信息\n· 工作与实习经历\n· 教育背景\n· 技能清单',
    jdPlaceholder: '在此粘贴目标岗位描述...\n\n建议包含：\n· 核心职责\n· 任职要求\n· 加分技能项',
    generateAnalysis: '生成分析报告',
    synthesizing: 'AI 深度分析中...',
    analysisReport: '分析报告',
    generatedBy: '由 Resume AI 引擎生成',
    waitingInput: '等待输入。分析报告将以专业的编辑级排版在此呈现。',
    chars: '字',
  }
};
